services:
  app:
    extends:
      file: compose.common.yaml
      service: app
    container_name: go-dev-app
    depends_on:
      - postgres-slave1

  cron:
    extends:
      file: compose.common.yaml
      service: app
    container_name: go-dev-cron
    command: "./build/scheduler"
    depends_on:
      - app

  postgres-master:
    extends:
      file: compose.common.yaml
      service: postgres
    container_name: go-dev-db-master
    environment:
      POSTGRESQL_REPLICATION_MODE: master
    volumes:
      - go-dev-postgres17-master:/bitnami/postgresql

  postgres-slave1:
    extends:
      file: compose.common.yaml
      service: postgres
    container_name: go-dev-db-slave1
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: postgres-master
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
    volumes:
      - go-dev-postgres17-slave1:/bitnami/postgresql
    depends_on:
      - postgres-master

volumes:
  go-dev-postgres17-master:
    name: go-dev-postgres17-master
  go-dev-postgres17-slave1:
    name: go-dev-postgres17-slave1
