services:
  app:
    extends:
      file: compose.common.yaml
      service: app
    container_name: vep-app
    volumes:
      - ./.env:/srv/.env
      - ./web:/srv/web
      #- ./migrations:/srv/migrations
    depends_on:
      - manticore

  cron:
    extends:
      file: compose.common.yaml
      service: app
    container_name: vep-cron
    command: "./build/scheduler"
    depends_on:
      - app
      - keydb

  consumer-pages:
    extends:
      file: compose.common.yaml
      service: app
    container_name: vep-consumer-pages
    command: "./build/consumer gr0 objects"
    depends_on:
      - cron

  manticore:
    container_name: vep-manticore
    image: manticoresearch/manticore:9.3.2
    environment:
      - EXTRA=1
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - vep-manticore-9:/var/lib/manticore

  keydb:
    container_name: vep-keydb
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    restart: unless-stopped
    volumes:
      - vep-keydb-6:/data

  redisinsight:
    container_name: vep-redisinsight
    image: redis/redisinsight:2.68.0
    volumes:
      - 'vep-redisinsight-2:/data'
    depends_on:
      - keydb

volumes:
  vep-manticore-9:
    name: vep-manticore-9
  vep-keydb-6:
    name: vep-keydb-6
  vep-redisinsight-2:
    name: vep-redisinsight-2
