services:
  app:
    extends:
      file: compose.common.yaml
      service: app
    container_name: go-dev-app
    depends_on:
      - postgres

  cron:
    extends:
      file: compose.common.yaml
      service: app
    container_name: go-dev-cron
    command: "./build/scheduler"
    depends_on:
      - app

  postgres:
    container_name: go-dev-db
    restart: unless-stopped
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - go-dev-postgres17:/var/lib/postgresql/data

volumes:
  go-dev-postgres17:
    name: go-dev-postgres17
