services:
  app:
    container_name: go-dev
    restart: unless-stopped
    build:
      context: .
    ports:
      - "127.0.0.90:80:8080"
    environment:
      PS1: "\\u:\\w$$ "
      #PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d_ext:/usr/local/etc/php/conf.d"
      #PHP_IDE_CONFIG: "serverName=127.0.0.7"
    #volumes:
    #  - ./docker/php/conf.d:/usr/local/etc/php/conf.d_ext
    #  - ./:/var/www
    #depends_on:
    #  - database
    #  - redis
      #- manticore
    #  - mailer