-- +goose Up
-- +goose StatementBegin
CREATE TABLE products (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL
);

INSERT INTO products (name) VALUES ('Xbox'), ('Playstation');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS products
-- +goose StatementEnd
