-- +goose Up
-- +goose StatementBegin
CREATE TABLE products (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    price numeric(12, 4) NOT NULL
);

INSERT INTO products (name, price) VALUES ('Xbox', 400.12), ('Playstation', 504.9);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS products
-- +goose StatementEnd
